apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: circleguard-stage

bases:
  - ../../base

commonLabels:
  environment: stage

patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment

images:
  - name: circleguard/auth-service
    newTag: stage
  - name: circleguard/identity-service
    newTag: stage
  - name: circleguard/form-service
    newTag: stage
  - name: circleguard/promotion-service
    newTag: stage
  - name: circleguard/notification-service
    newTag: stage
  - name: circleguard/gateway-service
    newTag: stage
